# Complete with tasks for:
# 1. compile everything
# 2. compile just boolean.c
# 3. compile just math.c
# 4. compile just strings.c

.PHONY: clean
clean:
	find . -name '*.o' -delete
	find . -name 'tutorial1' -delete